# Tuning Parameters

log_reg:
  C: [0.001, 0.01, 0.1, 1, 10, 100, 1000]
  penalty: ['l1', 'l2', 'elasticnet', 'none']
  solver: ['liblinear', 'saga', 'lbfgs', 'newton-cg']
  max_iter: [100, 1000, 10000]

# update in code: np.logspace(0,-9, num=1000)
naive_bayes:
  var_smoothing: []

svm:
  C: [0.1, 1, 10, 100, 1000]
  kernel: ['linear', 'rbf']
  gamma: ['scale', 'auto']
  coef0: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

knn:
  n_neighbors: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  weights: ['uniform', 'distance']
  algorithm: ['auto', 'ball_tree', 'kd_tree', 'brute']
  leaf_size: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
  p: [1, 2]

xgb:
  colsample_bytree: [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  gamma: [0.15, 0.2, 0.25, 0.3, 0.4]
  learning_rate: [0.001, 0.01, 0.05, 0.1]
  max_depth: [5, 6, 9, 10, 12, 15, 20]
  reg_lambda: [0.0, 0.5, 1.0, 1.25 , 1.5, 1.75, 2.0]
  subsample: [0.5, 0.8, 1.0, 1.5, 2.0, 3.0]